### ISSUE TITLE
Serialization error: com.alibaba.com.caucho.hessian.io.HessianProtocolException 

### ISSUE THREAD

**Issue by keepongjl** [alibaba/dubbo#1009]
[2017-12-06 17:24:08,271] [New I/O server worker #1-6] [WARN] [documentNumGenerator] com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation  [DUBBO] Decode rpc invocation failed: expected string at end of file, dubbo version: 2.5.3, current host: 10.8.148.45
com.alibaba.com.caucho.hessian.io.HessianProtocolException: expected string at end of file
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2720)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.expect(Hessian2Input.java:2683)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readString(Hessian2Input.java:1322)
	at com.alibaba.dubbo.common.serialize.support.hessian.Hessian2ObjectInput.readUTF(Hessian2ObjectInput.java:83)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:93)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:71)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:137)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:126)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:87)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:46)
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:134)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:761)

**Comment by keepongjl** [comment]
是文件最后的字符串解码出现错误了？hession序列化的问题？看了源码，大致是对输入的流进行读取字符串，然后switch语句匹配不上，之后抛出的异常。有遇见过的吗？之前看见过map类型，我这个是String类型，我们这里加了个基于jmx的监控，收集一些内存、线程等信息，之后发给zookeeper，但是上面配置的是1秒钟一次，而这上面有段好长的日志都是15秒一次

**Comment by keepongjl** [comment]
现在在测试环境上面也出现这问题了，之前测试没有，我将测试zk的监控monitor打开之后有的这个异常，之后在将序列化协议改为java还是不行，将配置文件的监控注掉还是有错，暂排除向监控发送数据序列化解析错误，或者java协议的序列化也不能解决这个字符串编码问题
