### ISSUE TITLE
增加 EnableDubbo 简化 Annotation

### ISSUE THREAD

**Issue by mercyblitz** [alibaba/dubbo#1015]
`@EnableDubbo` 等价于
`@DubboComponentScan` 与 `@EnableDubboConfig` 组合：

### 服务端配置

```java
@EnableDubbo(basePackages = "com.alibaba.dubbo.config.spring.context.annotation")
@PropertySource("META-INF/dubbb-provider.properties")
@EnableTransactionManagement
public static class TestProviderConfiguration {
}
```

`dubbo-provider.properties`:
```properties
# Dubbo Provider Properties as an alternative for
# Spring XML Bean definition : META-INF/spring/dubbo-annotation-provider.xml

demo.service.application = dubbo-annotation-provider
demo.service.protocol = dubbo
demo.service.registry = my-registry


## Dubbo configs binding properties

### <dubbo:application name="dubbo-annotation-provider"/>
dubbo.application.id = dubbo-annotation-provider
dubbo.application.name = Dubbo Provider

### <dubbo:registry id="my-registry" address="N/A"/>
dubbo.registry.id = my-registry
dubbo.registry.address = N/A

### <dubbo:protocol name="dubbo" port="12345"/>
dubbo.protocol.id = dubbo
dubbo.protocol.name = dubbo
dubbo.protocol.port = 12345
```

### 客户端配置

```java
@EnableDubbo(basePackageClasses = TestConsumerConfiguration.class, multipleConfig = true)
@PropertySource("META-INF/dubbb-consumer.properties")
@EnableTransactionManagement
public class TestConsumerConfiguration {
}
```

`META-INF/dubbb-consumer.properties`

```properties
# Dubbo Consumer Properties as an alternative for
# Spring XML Bean definition : META-INF/spring/dubbo-annotation-consumer.xml

demo.service.application = dubbo-annotation-consumer
demo.service.registry = my-registry

## Dubbo configs binding properties
###  <dubbo:application name="dubbo-annotation-consumer"/>
dubbo.application.dubbo-annotation-consumer.name = Dubbo Consumer
dubbo.application.dubbo-annotation-consumer2.name = dubbo-consumer2

### <dubbo:registry id="my-registry" address="N/A"/>
dubbo.registry.my-registry.address = N/A
dubbo.registry.my-registry2.address = N/A
```

**Comment by chickenlj** [comment]
我不理解consumer端的两处配置：
```xml
###  <dubbo:application name="dubbo-annotation-consumer"/>
dubbo.application.dubbo-annotation-consumer.name = Dubbo Consumer
dubbo.application.dubbo-annotation-consumer2.name = dubbo-consumer2

### <dubbo:registry id="my-registry" address="N/A"/>
dubbo.registry.my-registry.address = N/A
dubbo.registry.my-registry2.address = N/A
```

**Comment by mercyblitz** [comment]
@chickenlj 
```properties
###  <dubbo:application name="dubbo-annotation-consumer"/>
dubbo.application.dubbo-annotation-consumer.name = Dubbo Consumer
dubbo.application.dubbo-annotation-consumer2.name = dubbo-consumer2
```

以上定义为`AppicationConfig` 多 Bean 的定义方式，比如如果应用上下文只有一个`AppicationConfig` Bean 的话，那么，只需要如下定义：
```properties
dubbo.application.id = app-id
dubbo.application.name =  app-name
```

如果仅支持`dubbo.application.id`的话，对于`AppicationConfig` 还可以理解。如果需要多注册中心的的话，`RegistryConfig` 多Bean 定义需要配置支持。

**Comment by chickenlj** [comment]
Mark. 
如开启@EnableDubbo(multiConfig = true), 则所有配置项都必须使用多Bean模式配置，即：
```properties
dubbo.registry.registry1.address=xxx
```

**Comment by willlau0524** [comment]
赞，希望Spring Boot相关的使用文档可以更加详细

**Comment by mercyblitz** [comment]
@willlau0524 本周发布

**Comment by cwt9562** [comment]
我使用yml文件配置这3个配置项, 好像并不生效

dubbo.protocol.id = dubbo
dubbo.protocol.name = dubbo
dubbo.protocol.port = 12345

我的配置文件:
```
dubbo:
  application:
    name: showcase-provider
  registry:
    address: zookeeper://x.x.x.x:2181
  protocol:
    id: dubbo
    name: dubbo
    port: 30000
```
启动日志中看到的:
```
2018-01-03 10:04:57.302  INFO 5004 --- [  restartedMain] c.a.d.r.zookeeper.ZookeeperRegistry      :  [DUBBO] Notify urls for subscribe url provider://x.x.x.x:20880/xxx
```

**Comment by cwt9562** [comment]
调查结果:
在读取配置项的时候, 会调用到这个方法
com.alibaba.dubbo.config.spring.util.PropertySourcesUtils#getSubProperties
这个方法里写着value是String才放入map中
```
public static Map<String, String> getSubProperties(PropertySources propertySources, String prefix) {

        Map<String, String> subProperties = new LinkedHashMap<String, String>();

        String normalizedPrefix = prefix.endsWith(".") ? prefix : prefix + ".";

        for (PropertySource<?> source : propertySources) {
            if (source instanceof EnumerablePropertySource) {
                for (String name : ((EnumerablePropertySource<?>) source).getPropertyNames()) {
                    if (name.startsWith(normalizedPrefix)) {
                        String subName = name.substring(normalizedPrefix.length());
                        Object value = source.getProperty(name);
                        if (value instanceof String) {
                            subProperties.put(subName, String.valueOf(value));
                        }
                    }
                }
            }
        }

        return subProperties;

    }
```

而配置项dubbo.protocol.port是Integer


线程堆栈:
```
restartedMain@1690" prio=5 tid=0x14 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.alibaba.dubbo.config.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:40)
	  at com.alibaba.dubbo.config.spring.context.annotation.DubboConfigBindingRegistrar.registerDubboConfigBeans(DubboConfigBindingRegistrar.java:72)
	  at com.alibaba.dubbo.config.spring.context.annotation.DubboConfigBindingRegistrar.registerBeanDefinitions(DubboConfigBindingRegistrar.java:61)
	  at com.alibaba.dubbo.config.spring.context.annotation.DubboConfigBindingsRegistrar.registerBeanDefinitions(DubboConfigBindingsRegistrar.java:38)
```

**Comment by cwt9562** [comment]
解决方案:
在yml文件中, 将port指定为字符串
```
dubbo:
  protocol:
    port: "30000"
```

**Comment by mercyblitz** [comment]
@cwt9562 Spring did not provider the Yaml loader , Spring Boot did！
