### ISSUE TITLE
server elapsed超时时间离奇求解

### ISSUE THREAD

**Issue by carlvine500** [alibaba/dubbo#103]
``` java
com.alibaba.dubbo.rpc.RpcException: Invoke remote method timeout. method: hgetAll, provider: dubbo://10.58.22.193:20990/com.org.x.RedisService?anyhost=true&application=org.x-cache-redis-client-app-atg&check=false&delay=10000&dubbo=2.5.3&interface=com.org.x.RedisService&loadbalance=random&methods=lpush,hexists,hmset,decr,set,hsetnx,lpop,type,hlen,rpush,hincrBy,hgetAll,setex,ltrim,smembers,del,substr,incrBy,lrem,decrBy,expire,append,srem,hmget,llen,hget,lindex,get,hdel,keys,expireAt,ttl,sadd,mutliExecute,hset,rpop,exists,dbSize,scard,incr,hkeys,testDubboRequest,lrange&pid=14604&revision=1.1.0-SNAPSHOT&side=consumer&timeout=10000&timestamp=1422011641069, cause: Waiting server-side response timeout. start time: 2015-01-24 16:59:13.883, end time: 2015-01-24 16:59:54.950, client elapsed: 0 ms, server elapsed: 41067 ms, timeout: 10000 ms, request: Request [id=10246398, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=hgetAll, parameterTypes=[class java.lang.String, class java.lang.String], arguments=[BUDGET, C8100239023_case], attachments={path=com.org.x.RedisService, interface=com.org.x.RedisService, timeout=10000, version=0.0.0}]], channel: /10.58.22.213:54977 -> /10.58.22.193:20990
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:99)
        at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
        at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
        at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
        at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
        at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227)
        at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
        at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
        at com.alibaba.dubbo.common.bytecode.proxy0.hgetAll(proxy0.java)
        at com.org.x.cache.impl.RemoteCacheToolImpl.hgetAll(RemoteCacheToolImpl.java:105)
        at com.org.x.cache.impl.CacheRedisToolImpl.hgetAll(CacheRedisToolImpl.java:67)
        at com.org.x.commerce.order.submitordervalidator.basetools.BudgetManageService.allValidCases(BudgetManageService.java:458)
        at com.org.x.commerce.order.submitordervalidator.basetools.BudgetManageService.cacheValidCase(BudgetManageService.java:445)
        at com.org.x.commerce.promotion.Loadorg.xBudgetCaseSchedule.performSchedule(Loadorg.xBudgetCaseSchedule.java:19)
        at com.org.x.commerce.estore.org.xBaseSchedule.performScheduledTask(org.xBaseSchedule.java:93)
        at atg.service.scheduler.Scheduler.handleNextScheduledJob(Scheduler.java:481)
        at atg.service.scheduler.Scheduler.handleScheduledJobs(Scheduler.java:663)
        at atg.service.scheduler.Scheduler$Polle
```

**Comment by sorra** [comment]
是不是实际超时时间大于超时上限设置？
我们也遇到了，调用方设200ms上限，有时会等待500ms。

**Comment by zackszhang** [comment]
这个问题怎么没人解决就关闭了?
