### ISSUE TITLE
[Dubbo 2.5.8] Telnet failed with 'java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils'

### ISSUE THREAD

**Issue by nobodyiam** [alibaba/dubbo#1132]
Hi there,

Looks like dubbo missed the transitive dependency of `org.apache.commons:commons-lang3` which will cause `java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils` when executing telnet command like `ls`.

### 1. Create a dubbo demo server with dubbo 2.5.8 dependency and no `org.apache.commons:commons-lang3`

```xml
  <dependencies>
    <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>dubbo</artifactId>
      <version>2.5.8</version>
    </dependency>
  </dependencies>
```
### 4. Check the server log, you will find the following error logs

>java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at com.alibaba.dubbo.qos.server.handler.TelnetProcessHandler.channelRead0(TelnetProcessHandler.java:34) ~[dubbo-2.5.8.jar:2.5.8]
	at com.alibaba.dubbo.qos.server.handler.TelnetProcessHandler.channelRead0(TelnetProcessHandler.java:26) ~[dubbo-2.5.8.jar:2.5.8]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:217) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:640) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:463) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:426) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at com.alibaba.dubbo.qos.server.handler.QosProcessHandler.decode(QosProcessHandler.java:77) [dubbo-2.5.8.jar:2.5.8]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_74]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_74]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]
	... 33 more

### 5. How to fix?

To be honest, I'm not sure why the `dubbo-qos` module uses the `org.apache.commons:commons-lang3` which is not used anywhere else in dubbo.

Looks like the previous pull request #982 introduced this dependency. However, this dependency is excluded in [dubbo/pom.xml](https://github.com/alibaba/dubbo/blob/master/dubbo/pom.xml#L273)! Which is quite unreasonable.

The fact is it's not common that every java project will include the `org.apache.commons:commons-lang3` dependency.

So my suggestion is either to refactor the `dubbo-qos` module and remove `org.apache.commons:commons-lang3` or add it as a transitive dependency of dubbo.

**Comment by chickenlj** [comment]
We have tried to avoid introduce a new dependency with `dubbo-qos`, but the output of telnet needs to be formatted and it is pretty tricky. 

I think add `commons-lang3` as transitive dependency is not a good choice as it may cause some implicit dependency conflicts.

1. We can add a instruction in [documentation](http://dubbo.io/books/dubbo-user-book/references/qos.html), declaring that `commons-lang3` is a necessary for `dubbo-qos` module, and also this can be quite reasonable when we user can decide whether to use `dubbo-qos` or not. Also see #1073.
2. We can discuss the possibility of avoid using `commons-lang3` again.

**Comment by nobodyiam** [comment]
Thanks for the quick response!

Currently, according to the [code](https://github.com/alibaba/dubbo/blob/master/dubbo-plugin/dubbo-qos/src/main/java/com/alibaba/dubbo/qos/server/Server.java#L81), the qos module is enabled by default and has no option to turn it off.

If a new option like `telnet.open=true/false` could be added, then I think it's reasonable the user should follow the instructions to enable this feature with an explicit dependency.

**Comment by chickenlj** [comment]
We have add `dubbo.application.qos.enable=true/false` as a switch for qos, and `commons-lang3` is still not transitive.

**Comment by nobodyiam** [comment]
Thanks!
