### ISSUE TITLE
com.caucho.hessian.io.HessianProtocolException: '￿' is an unknown code

### ISSUE THREAD

**Issue by xishian** [alibaba/dubbo#1136]
使用dubbo传输文件到server进行解析，接口大概如下
String parseFile(String filename,InputStream is);
对于大部分文件都成功执行，但是解析某几个文件时，出现了异常：
Service端：
 com.caucho.hessian.io.HessianProtocolException: parseAttachmetToJsonByInputStream: expected end of call ('z') at 0x62 (b).  Check method arguments and ensure method overloading is enabled if necessary

Consumer端：
Exception in thread "main" com.caucho.hessian.client.HessianRuntimeException: com.caucho.hessian.io.HessianProtocolException: '￿' is an unknown code
	at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:221)
	**at com.sun.proxy.$Proxy6.parseFileToJsonByInputStream(Unknown Source)**
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.dubbo.rpc.proxy.jdk.JdkProxyFactory$1.doInvoke(JdkProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.AbstractProxyProtocol$2.doInvoke(AbstractProxyProtocol.java:95)
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:229)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
	at com.sun.proxy.$Proxy8.parseAttachmetToJsonByInputStream(Unknown Source)
	at com.netease.attachmentservice.consumer.DemoConsumer.main(DemoConsumer.java:55)
Caused by: com.caucho.hessian.io.HessianProtocolException: '￿' is an unknown code
	at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:219)
	... 23 more
dubbo使用的是Hessian协议

**Comment by xishian** [comment]
使用Hessian传InputStream时，如果流被关闭但实际上流里面还有数据就会出现这种错误。解决办法也很简单，把剩余的数据读出来就行了。

**Comment by chickenlj** [comment]
> Check method arguments and ensure method overloading is enabled if necessary

Currently, hessian integration on dubbo doesn't support override of service methods, check if you have method override?

**Comment by kingravi17** [comment]
Is this issue resolved? Am also facing a similar issue intermittently.

Or is there any workaround available?

Exception org.springframework.remoting.RemoteAccessException: Cannot access Hessian remote service at [http://******]; nested exception is com.caucho.hessian.io.HessianProtocolException: '￿' is an unknown code
	at org.springframework.remoting.caucho.HessianClientInterceptor.convertHessianAccessException(HessianClientInterceptor.java:266)
	at org.springframework.remoting.caucho.HessianClientInterceptor.invoke(HessianClientInterceptor.java:235)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
