### ISSUE TITLE
The process is blocked by `pool-3-thread-1{Hashed wheel timer #2}` and can't shutdown, dubbo version is 2.5.8

### ISSUE THREAD

**Issue by liuzhen2012001** [alibaba/dubbo#1155]
项目加载elasticsearch 2.1.1版本，dubbo 2.5.8版本 pool-3-thread-1{Hashed wheel timer #2}进程无法退出，导致无法停机
"pool-3-thread-1{Hashed wheel timer #2}" prio=6 tid=0x000000000fcde000 nid=0x2104 waiting on condition [0x00000000176ff000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.jboss.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:445)
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:364)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at java.lang.Thread.run(Thread.java:745)

**Comment by chickenlj** [comment]
Have you confirmed that your process is blocked by this thread?
And have you use netty in your project for other purpose and did not release resources correctly?

**Comment by liuzhen2012001** [comment]
netty包冲突了，项目中使用了3.10.x的高版本的netty包，高版本的netty包在 new HashedWheelTimer时候设置了非守护线程。dubbo在创建NettyClient时候进入了高版本的netty中，引进了这个线程，导致Tomcat停不下来，目前做法是 通过修改netty，让HashedWheelTimer变成守护线程，暂时解决了这个问题
