### ISSUE TITLE
dubbo-monitor can not generate charts.

### ISSUE THREAD

**Issue by liurongwei** [alibaba/dubbo#1162]
**绘图时显示数组超出边界：
2018-01-03 19:20:54,504 [DubboMonitorTimer-thread-1] ERROR com.alibaba.dubbo.monitor.simple.SimpleMonitorService$2 (SimpleMonitorService.java:102) - [DUBBO] Unexpected error occur at draw stat chart, cause: 0, dubbo version: 2.5.8, current host: 192.168.0.195
java.lang.ArrayIndexOutOfBoundsException: 0
at sun.font.CompositeStrike.getStrikeForSlot(CompositeStrike.java:75)
at sun.font.CompositeStrike.getFontMetrics(CompositeStrike.java:93)
at sun.font.FontDesignMetrics.initMatrixAndMetrics(FontDesignMetrics.java:359)
at sun.font.FontDesignMetrics.(FontDesignMetrics.java:350)
at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:302)
at sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:863)
at org.jfree.text.TextFragment.calculateDimensions(TextFragment.java:229)
at org.jfree.text.TextLine.calculateDimensions(TextLine.java:190)
at org.jfree.text.TextBlock.calculateDimensions(TextBlock.java:171)
at org.jfree.chart.block.LabelBlock.arrange(LabelBlock.java:316)
at org.jfree.chart.block.BorderArrangement.arrangeNN(BorderArrangement.java:210)
at org.jfree.chart.block.BorderArrangement.arrange(BorderArrangement.java:137)
at org.jfree.chart.block.BlockContainer.arrange(BlockContainer.java:179)
at org.jfree.chart.block.CenterArrangement.arrangeNN(CenterArrangement.java:284)
at org.jfree.chart.block.CenterArrangement.arrange(CenterArrangement.java:98)
at org.jfree.chart.block.BlockContainer.arrange(BlockContainer.java:179)
at org.jfree.chart.block.FlowArrangement.arrangeNN(FlowArrangement.java:365)
at org.jfree.chart.block.FlowArrangement.arrangeRR(FlowArrangement.java:283)
at org.jfree.chart.block.FlowArrangement.arrange(FlowArrangement.java:158)
at org.jfree.chart.block.BlockContainer.arrange(BlockContainer.java:179)
at org.jfree.chart.title.LegendTitle.arrange(LegendTitle.java:501)
at org.jfree.chart.JFreeChart.drawTitle(JFreeChart.java:1330)
at org.jfree.chart.JFreeChart.draw(JFreeChart.java:1220)
at org.jfree.chart.JFreeChart.createBufferedImage(JFreeChart.java:1409)
at org.jfree.chart.JFreeChart.createBufferedImage(JFreeChart.java:1389)
at org.jfree.chart.JFreeChart.createBufferedImage(JFreeChart.java:1374)
at com.alibaba.dubbo.monitor.simple.SimpleMonitorService.createChart(SimpleMonitorService.java:139)
at com.alibaba.dubbo.monitor.simple.SimpleMonitorService.draw(SimpleMonitorService.java:309)
at com.alibaba.dubbo.monitor.simple.SimpleMonitorService.access$300(SimpleMonitorService.java:62)
at com.alibaba.dubbo.monitor.simple.SimpleMonitorService$2.run(SimpleMonitorService.java:100)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)**

**Comment by chickenlj** [comment]
I am sorry about that, we are planning to refactor this part, but we still don't have time at this moment. 
Here's one open source implementations for your reference: [dubbo-monitor](https://gitee.com/handu/dubbo-monitor)
