### ISSUE TITLE
When using -Djava.ext.dirs to load libs of projects, the following exceptions occur with generic call.

### ISSUE THREAD

**Issue by linuke** [alibaba/dubbo#1228]
Caused by: com.alibaba.dubbo.remoting.RemotingException: Failed to send message Request [id=147, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=$invoke, parameterTypes=[class java.lang.String, class [Ljava.lang.String;, class [Ljava.lang.Object;], arguments=[driverDayInfo, [Ljava.lang.String;@2a16bc2, [Ljava.lang.Object;@c6685e6], attachments={path=xxxxxxxx, interface=xxxxxxxxxxxx, version=1.0, generic=true, timeout=3000}]] to /121.43.35.97:7073, cause: tried to access method com.alibaba.dubbo.common.serialize.support.dubbo.GenericDataOutput.write0(B)V from class com.alibaba.dubbo.common.serialize.support.dubbo.Builder$bc0
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:108)
	at com.alibaba.dubbo.remoting.transport.AbstractClient.send(AbstractClient.java:258)
	at com.alibaba.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:54)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.request(HeaderExchangeChannel.java:112)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeClient.request(HeaderExchangeClient.java:88)
	at com.alibaba.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient.request(ReferenceCountExchangeClient.java:78)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:97)
	... 69 common frames omitted
Caused by: java.lang.IllegalAccessError: tried to access method com.alibaba.dubbo.common.serialize.support.dubbo.GenericDataOutput.write0(B)V from class com.alibaba.dubbo.common.serialize.support.dubbo.Builder$bc0
	at com.alibaba.dubbo.common.serialize.support.dubbo.Builder$bc0.writeTo(Builder$bc0.java)
	at com.alibaba.dubbo.common.serialize.support.dubbo.GenericObjectOutput.writeObject(GenericObjectOutput.java:82)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.encodeRequestData(DubboCodec.java:177)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encodeRequest(ExchangeCodec.java:229)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:39)
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:81)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:66)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292)
	at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:99)
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
	at org.jboss.netty.channel.Channels.write(Channels.java:704)
	at org.jboss.netty.channel.Channels.write(Channels.java:671)
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:347)
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:98)
	... 75 common frames omitted

**Comment by foreveryang321** [comment]
使用-Djava.ext.dirs=xxx会覆盖掉默认的jre ext lib的配置，可以试一下-Dloader.path=xxx

**Comment by chickenlj** [comment]
I think this is most likely to be a problem caused by `-Djava.ext.dirs`. Maybe you can follow what @foreveryang321 suggests.

Also, we don't recommend using the `embedded JSON implementation`
