### ISSUE TITLE
springBoot+Dubbo报错

### ISSUE THREAD

**Issue by panchen66** [alibaba/dubbo#1253]
启动客户端连接服务端后，定期报错：
   com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method subscribe in the service com.alibaba.dubbo.registry.RegistryService. Tried 3 times of the providers [192.168.10.226:2181] (1/1) from the registry 192.168.10.226:2181 on the consumer 192.168.10.70 using the dubbo version 2.5.3. Last error is: Invoke remote method timeout. method: subscribe, provider: dubbo://192.168.10.226:2181/com.alibaba.dubbo.registry.RegistryService?application=tq_examinationTraining_consumer&callbacks=10000&check=false&connect.timeout=10000&dubbo=2.5.3&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=7544&reconnect=false&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1516612316899&unsubscribe.1.callback=false, cause: Waiting server-side response timeout. start time: 2018-01-22 17:12:57.149, end time: 2018-01-22 17:13:07.158, client elapsed: 8 ms, server elapsed: 10001 ms, timeout: 10000 ms, request: Request [id=8, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=subscribe, parameterTypes=[class com.alibaba.dubbo.common.URL, interface com.alibaba.dubbo.registry.NotifyListener], arguments=[consumer://192.168.10.70/com.alibaba.dubbo.registry.RegistryService?application=tq_examinationTraining_consumer&callbacks=10000&connect.timeout=10000&dubbo=2.5.3&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=7544&reconnect=false&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1516612316899&unsubscribe.1.callback=false, com.alibaba.dubbo.registry.integration.RegistryDirectory@35bfa1bb], attachments={path=com.alibaba.dubbo.registry.RegistryService, sys_callback_arg-1=901751227, interface=com.alibaba.dubbo.registry.RegistryService, version=0.0.0, timeout=10000}]], channel: 192.168.10.70:0 -> /192.168.10.226:2181
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:101) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.common.bytecode.proxy0.subscribe(proxy0.java) ~[na:2.5.3]
	at com.alibaba.dubbo.registry.dubbo.DubboRegistry.doSubscribe(DubboRegistry.java:138) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.registry.support.FailbackRegistry.retry(FailbackRegistry.java:362) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.registry.support.FailbackRegistry$1.run(FailbackRegistry.java:67) [dubbo-2.5.3.jar:2.5.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_73]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_73]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_73]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]
Caused by: com.alibaba.dubbo.remoting.TimeoutException: Waiting server-side response timeout. start time: 2018-01-22 17:12:57.149, end time: 2018-01-22 17:13:07.158, client elapsed: 8 ms, server elapsed: 10001 ms, timeout: 10000 ms, request: Request [id=8, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=subscribe, parameterTypes=[class com.alibaba.dubbo.common.URL, interface com.alibaba.dubbo.registry.NotifyListener], arguments=[consumer://192.168.10.70/com.alibaba.dubbo.registry.RegistryService?application=tq_examinationTraining_consumer&callbacks=10000&connect.timeout=10000&dubbo=2.5.3&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=7544&reconnect=false&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1516612316899&unsubscribe.1.callback=false, com.alibaba.dubbo.registry.integration.RegistryDirectory@35bfa1bb], attachments={path=com.alibaba.dubbo.registry.RegistryService, sys_callback_arg-1=901751227, interface=com.alibaba.dubbo.registry.RegistryService, version=0.0.0, timeout=10000}]], channel: 192.168.10.70:0 -> /192.168.10.226:2181
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:107) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:96) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77) ~[dubbo-2.5.3.jar:2.5.3]
	... 14 common frames omitted

**Comment by panchen66** [comment]
spring.dubbo.registry.address=127.0.0.1:2181
spring.dubbo.scan=com.tianque.examinationTraining.user.controller


@Controller
public class UserController {
	
	private Logger logger = LoggerFactory.getLogger(getClass());
	
	@Reference
	public CallUserService callUserService;
	
	/**
	 * 用户中心登陆
	 */
	@RequestMapping(value = "/user/login", method = RequestMethod.GET)
	private @ResponseBody ResultMsg login(User user) {
	/*	try {*/
			if (null == user) {
				return new ResultMsg(false, "信息不能为空!", null);
			}
			if (null == user.getName()) {
				return new ResultMsg(false, "账号名称不能为空!", null);
			}
			if (null == user.getPassword()) {
				return new ResultMsg(false, "密码不能为空!", null);
			}
			UserDTO userDTO=callUserService.findUserByUserName(user.getName());
			if(null!=userDTO){
				return new ResultMsg(true, "登录成功!", null);
			}
			return new ResultMsg(false, "账号不存在或密码错误,请检查!", null);
	/*	} catch (BusinessException e) {
			logger.error(e.getMessage());
			return new ResultMsg(false, e.getMessage(), null);
		} catch (Exception e) {
			logger.error("登录失败!", e.getMessage());
			return new ResultMsg(false, "登录成功!", null);
		}*/
	}
}


报错：com.alibaba.dubbo.common.logger.Logger   :  [DUBBO] Failed to init remote service reference at filed callUserService in class com.tianque.examinationTraining.user.controller.UserController, cause: null, dubbo version: 2.5.3, current host: 127.0.0.1
