### ISSUE TITLE
NoClassDefFoundError using kryo

### ISSUE THREAD

**Issue by hank-whu** [alibaba/dubbo#1266]
mvn中已经添加了 kryo-4.0.1 的依赖

Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.dubbo.common.serialize.support.kryo.utils.KryoUtils
	at com.alibaba.dubbo.common.serialize.support.kryo.KryoObjectOutput.<init>(KryoObjectOutput.java:36)
	at com.alibaba.dubbo.common.serialize.support.kryo.KryoSerialization.serialize(KryoSerialization.java:43)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encodeRequest(ExchangeCodec.java:227)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:70)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:37)
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:80)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:66)
	at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:98)
	at org.jboss.netty.channel.Channels.write(Channels.java:611)
	at org.jboss.netty.channel.Channels.write(Channels.java:578)
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:251)
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:96)
	... 31 more

**Comment by sky-syk** [comment]
spring中是否已经扫描 包

**Comment by imadcn** [comment]
新版的功能需要手动添加pom依赖
你看 https://github.com/alibaba/dubbo/releases/tag/dubbo-2.6.0
的 **Important Notes** 部分

**Comment by sky-syk** [comment]
我是说你的spring扫对应的kryo的包了么. scan

**Comment by hank-whu** [comment]
使用kryo序列化还跟spring有关系？
要怎样扫描，有文档吗？

**Comment by chickenlj** [comment]
Have you checked that kryo is in your classpath?

**Comment by hank-whu** [comment]
@chickenlj 
Yes, I have added kryo-4.0.1 in pom.xml

**Comment by hank-whu** [comment]
整明白了，除了 kryo 还需要添加 de.javakaffee:kryo-serializers 的依赖。
建议你们文档添加下说明，至少报错时提示下也行。

**Comment by chickenlj** [comment]
We will take it, thanks for you advice.

**Comment by horsen689** [comment]
2018年到现在文档：示例>Kryo和FST序列化  里还没有写上这个坑

**Comment by asahouse** [comment]
到2021年还未填上这个坑，且“kryo-serializers”已经弃坑只支持kryo最高到4.0版本，现在的5.0是用不上在dubbo项目的了。大家要慎用。
