### ISSUE TITLE
Maven build failed on Java 9

### ISSUE THREAD

**Issue by ralf0131** [alibaba/dubbo#1283]
Trying to build Dubbo on Java 9, I got build failure with the following stack trace:

```
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116)
        at java.base/java.lang.String.substring(String.java:1885)
        at org.apache.commons.lang.SystemUtils.getJavaVersionAsFloat(SystemUtils.java:1133)
        at org.apache.commons.lang.SystemUtils.<clinit>(SystemUtils.java:818)
        ... 59 more
```

Looks like commons-lang does not understand the version semantics of Java 9.

**Comment by ralf0131** [comment]
It is the maven-javadoc-plugin's bad, which contains lower version of commons-lang dependency that is not compatible with Java 9. Updating version to 3.0.0 will solve this issue. I will send out PR later.
