### ISSUE TITLE
Kryo exception in 2.6.0. Could not initialize class com.alibaba.dubbo.common.serialize.support.kryo.utils.KryoUtils

### ISSUE THREAD

**Issue by iGitHubJ** [alibaba/dubbo#1285]
Exception in thread "main" com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method getAppUserBaseInfo in the service com.go.commons.api.service.UserServiceApi. Tried 3 times of the providers [192.168.10.194:20880] (1/1) from the registry 192.168.10.137:6379 on the consumer 192.168.10.194 using the dubbo version 2.6.0. Last error is: Failed to invoke remote method: getAppUserBaseInfo, provider: dubbo://192.168.10.194:20880/com.go.commons.api.service.UserServiceApi?accesslog=true&anyhost=true&application=consumer-dubbo&cache=lru&check=false&default.serialization=kryo&default.timeout=5000&dubbo=2.6.0&generic=false&interface=com.go.commons.api.service.UserServiceApi&logger=slf4j&methods=getAppUserBaseInfo,updateLocation,checkAuth,updateAppUserStatus&pid=3380&register.ip=192.168.10.194&remote.timestamp=1516958989309&retries=2&side=consumer&timeout=10000&timestamp=1516959000337&validation=true, cause: Failed to send message Request [id=2, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=getAppUserBaseInfo, parameterTypes=[class java.lang.Integer], arguments=[10], attachments={path=com.go.commons.api.service.UserServiceApi, interface=com.go.commons.api.service.UserServiceApi, version=0.0.0, timeout=10000}]] to /192.168.10.194:20880, cause: Could not initialize class com.alibaba.dubbo.common.serialize.support.kryo.utils.KryoUtils
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:101)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:232)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:70)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:51)
	at com.alibaba.dubbo.common.bytecode.proxy0.getAppUserBaseInfo(proxy0.java)
	at com.go.test.DubboTest.main(DubboTest.java:11)
Caused by: com.alibaba.dubbo.remoting.RemotingException: Failed to send message Request [id=2, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=getAppUserBaseInfo, parameterTypes=[class java.lang.Integer], arguments=[10], attachments={path=com.go.commons.api.service.UserServiceApi, interface=com.go.commons.api.service.UserServiceApi, version=0.0.0, timeout=10000}]] to /192.168.10.194:20880, cause: Could not initialize class com.alibaba.dubbo.common.serialize.support.kryo.utils.KryoUtils

**Comment by chickenlj** [comment]
#1266

**Comment by joytismile** [comment]
how did you solve the problem,and I meet the same problem
