### ISSUE TITLE
Failed to retriving ip address

### ISSUE THREAD

**Issue by onforyou** [alibaba/dubbo#1338]
com.alibaba.dubbo.common.utils.NetUtils- [DUBBO] Failed to retriving ip address, ip6-localhost: ip6-localhost: Name or service not known, dubbo version: 2.5.3, current host: 127.0.0.1
java.net.UnknownHostException: ip6-localhost: ip6-localhost: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress0(NetUtils.java:203)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress(NetUtils.java:190)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalHost(NetUtils.java:154)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:265)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:254)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:63)
	at com.alibaba.dubbo.rpc.Protocol$Adpative.refer(Protocol$Adpative.java)
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:392)
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:300)
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:138)
	at com.alibaba.dubbo.config.spring.AnnotationBean.refer(AnnotationBean.java:302)
	at com.alibaba.dubbo.config.spring.AnnotationBean.postProcessBeforeInitialization(AnnotationBean.java:233)

-----------

/etc/hosts

127.0.1.1       localhost.localdomain   localhost
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

**Comment by yangqun123** [comment]
修改hosts文件，第一行添加hostname 你自己的ip 试一下

**Comment by scuwuyu** [comment]
如果是Linux服务器，并且有别名的，检查 /etc/sysconfig/network 中的记录的 hostname 是否和 /etc/hosts 中的主机名绑定一致。

**Comment by onforyou** [comment]
把ip6-localhost 也 指向 127.0.0.1 了, 搞定
