### ISSUE TITLE
dubbo admin was installed successfully, but it keeps warning "Zookeeper is not connected yet"

### ISSUE THREAD

**Issue by 617972800** [alibaba/dubbo#1366]
dubbo admin安装后，provider和consumer可以正常发现，但总是出现警告提示 Zookeeper is not connected yet，感觉是dubbo  admin(193.0.10.128)一直在连接zookeeper://127.0.0.1:2181/，但配置文件我已经修改了（dubbo.registry.address=zookeeper://193.0.10.129:2181）。配置及报错信息如下：

dubbo admin修改如下：
vi webapps/ROOT/WEB-INF/dubbo.properties
dubbo.properties
dubbo.registry.address=zookeeper://193.0.10.129:2181
dubbo.admin.root.password=root
dubbo.admin.guest.password=guest

报错信息如下：
2018-02-11 14:42:52,991 [DubboRegistryFailedRetryTimer-thread-1] INFO  com.alibaba.dubbo.registry.support.FailbackRegistry (FailbackRegistry.java:369) -  [DUBBO] Retry subscribe {admin://193.0.10.128?category=providers,consumers,routers,configurators&check=false&classifier=*&enabled=*&group=*&interface=*&version=*=[com.alibaba.dubbo.governance.sync.RegistryServerSync@3d20aa1]}, dubbo version: 2.0.1, current host: 193.0.10.128
2018-02-11 14:42:52,991 [DubboRegistryFailedRetryTimer-thread-1] WARN  com.alibaba.dubbo.registry.support.FailbackRegistry (FailbackRegistry.java:380) -  [DUBBO] Failed to retry subscribe {admin://193.0.10.128?category=providers,consumers,routers,configurators&check=false&classifier=*&enabled=*&group=*&interface=*&version=*=[com.alibaba.dubbo.governance.sync.RegistryServerSync@3d20aa1]}, waiting for again, cause: Failed to subscribe admin://193.0.10.128?category=providers,consumers,routers,configurators&check=false&classifier=*&enabled=*&group=*&interface=*&version=* to zookeeper zookeeper://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=dubbo-admin&check=false&dubbo=2.0.1&file=false&interface=com.alibaba.dubbo.registry.RegistryService&pid=27985&timestamp=1518329932598, cause: Zookeeper is not connected yet!, dubbo version: 2.0.1, current host: 193.0.10.128
com.alibaba.dubbo.rpc.RpcException: Failed to subscribe admin://193.0.10.128?category=providers,consumers,routers,configurators&check=false&classifier=*&enabled=*&group=*&interface=*&version=* to zookeeper zookeeper://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=dubbo-admin&check=false&dubbo=2.0.1&file=false&interface=com.alibaba.dubbo.registry.RegistryService&pid=27985&timestamp=1518329932598, cause: Zookeeper is not connected yet!
        at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:185)
        at com.alibaba.dubbo.registry.support.FailbackRegistry.retry(FailbackRegistry.java:377)
        at com.alibaba.dubbo.registry.support.FailbackRegistry$1.run(FailbackRegistry.java:70)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Zookeeper is not connected yet!
        at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkClientWrapper.createPersistent(ZkClientWrapper.java:98)
        at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperClient.createPersistent(ZkclientZookeeperClient.java:61)
        at com.alibaba.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:63)
        at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:149)
        ... 9 more

**Comment by chickenlj** [comment]
It seems like that your modification of ZK address didn't take effect. Have you checked?

**Comment by 617972800** [comment]
嗯，本地IDEA启动没有报错，就是打包后在linux上运行会报错，配置是改了的

**Comment by 617972800** [comment]
嗯，本地IDEA启动没有报错，就是打包后在linux上运行会报错，配置是改了的

**Comment by chickenlj** [comment]
Have you find why it doesn't work?
I am sure dubbo-admin will read ZK configuration from dubbo.properties, please check.

**Comment by chenhongen** [comment]
然后怎么解决的呢。。

**Comment by vhwfif** [comment]
我的和你这个一样,我明明记得我改了zookeeper的地址,结果发现是没改....所以可能项目中某个地方的zookeeper地址还是本机地址还没修改.
