### ISSUE TITLE
使用Tomcat的shutdown，会报以下错误，这个是什么原因？

### ISSUE THREAD

**Issue by shine4net** [alibaba/dubbo#173]
Exception in thread "DubboShutdownHook" java.lang.NoClassDefFoundError: com/alibaba/dubbo/registry/support/AbstractRegistryFactory
	at com.alibaba.dubbo.config.ProtocolConfig.destroyAll(ProtocolConfig.java:429)
	at com.alibaba.dubbo.config.AbstractConfig$1.run(AbstractConfig.java:452)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.alibaba.dubbo.registry.support.AbstractRegistryFactory
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1858)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1709)
	... 3 more

**Comment by cuiyang-org** [comment]
看一下你的ZooKeeper版本是不是3.3.3。升级一下ZooKeeper版本试试。我用的是3.4.5。

**Comment by ralf0131** [comment]
Related issue #1665
