### ISSUE TITLE
NotSerializableException when use inputstream as paramter

### ISSUE THREAD

**Issue by chushiyun2015** [alibaba/dubbo#180]
public String upLoadImg(String suffix, InputStream in) throws Exception {}

when invoke above method, throw exception:
Caused by: java.io.NotSerializableException: java.io.SequenceInputStream
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.alibaba.dubbo.common.serialize.support.java.JavaObjectOutput.writeObject(JavaObjectOutput.java:64)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.encodeRequestData(DubboCodec.java:184)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encodeRequest(ExchangeCodec.java:236)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:75)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:39)
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:81)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:66)
	at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:99)
	at org.jboss.netty.channel.Channels.write(Channels.java:611)
	at org.jboss.netty.channel.Channels.write(Channels.java:578)
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:251)
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:98)
	... 93 more

**Comment by justein** [comment]
这个对象没法序列化，dubbo需要传输对象都实现了Serializable接口

**Comment by teaey** [comment]
beego

**Comment by chushiyun2015** [comment]
谢谢
是的 我已经知道原因了 并且通过byte数组来实现文件上传。
