### ISSUE TITLE
dubbo 2.5.3GenericFilter异常

### ISSUE THREAD

**Issue by lindzh** [alibaba/dubbo#203]
com.alibaba.dubbo.rpc.service.GenericException: java.lang.NullPointerException
java.lang.NullPointerException

	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:91)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lindzh** [comment]
说明下，业务代码都还没进入，直接异常了

**Comment by teaey** [comment]
dubbo 版本是

**Comment by lindzh** [comment]
2.5.3

2016-02-22 

linsony0 



发件人：wuxiaofei <notifications@github.com>
发送时间：2016-02-22 15:53
主题：Re: [dubbo] dubbo 2.5.3GenericFilter异常 (#203)
收件人："alibaba/dubbo"<dubbo@noreply.github.com>
抄送："lindzh"<linsony0@163.com>

dubbo 版本是

**Comment by lindzh** [comment]
2.5.3
这个问题后来跟踪了下，问题的根本原因是业务方抛出Null的bug，但是dubbo打的异常栈却是dubbo的，dubbo屏蔽了业务的异常栈，排查问题有log也很困难

2016-02-22 

linsony0 



发件人：wuxiaofei <notifications@github.com>
发送时间：2016-02-22 15:53
主题：Re: [dubbo] dubbo 2.5.3GenericFilter异常 (#203)
收件人："alibaba/dubbo"<dubbo@noreply.github.com>
抄送："lindzh"<linsony0@163.com>

dubbo 版本是
