### ISSUE TITLE
dubbo shutdown zk null pointer

### ISSUE THREAD

**Issue by lindzh** [alibaba/dubbo#207]
dubbo 在spring容器关闭的时候，会删除zookeeper中consumers的path，session close会出现close失败，抛出Null异常

``` java
java.lang.IllegalStateException: Failed to unregister dubbo://169.254.76.30:29999/com.linda.scheduler.api.remote.ScheduleApiExecutor?anyhost=true&application=aidaojia_test&dubbo=2.5.3&group=aidaojia&interface=com.linda.scheduler.api.remote.ScheduleApiExecutor&methods=executeTask&pid=8000&revision=1.0.0_test&side=provider&timestamp=1456745605949&version=1.0.0_test to registry 192.168.2.211:2181, cause: Failed to unregister dubbo://169.254.76.30:29999/com.linda.scheduler.api.remote.ScheduleApiExecutor?anyhost=true&application=aidaojia_test&dubbo=2.5.3&group=aidaojia&interface=com.linda.scheduler.api.remote.ScheduleApiExecutor&methods=executeTask&pid=8000&revision=1.0.0_test&side=provider&timestamp=1456745605949&version=1.0.0_test to zookeeper zookeeper://192.168.2.211:2181/com.alibaba.dubbo.registry.RegistryService?application=aidaojia_test&dubbo=2.5.3&interface=com.alibaba.dubbo.registry.RegistryService&pid=8000&timestamp=1456745605009, cause: null
    at com.alibaba.dubbo.registry.support.FailbackRegistry.unregister(FailbackRegistry.java:173)
    at com.alibaba.dubbo.registry.integration.RegistryProtocol$1.unexport(RegistryProtocol.java:130)
    at com.alibaba.dubbo.config.ServiceConfig.unexport(ServiceConfig.java:267)
    at com.alibaba.dubbo.config.spring.ServiceBean.destroy(ServiceBean.java:255)
    at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:239)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:510)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:486)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:751)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:455)
    at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1092)
    at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1066)
    at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:982)
Caused by: com.alibaba.dubbo.rpc.RpcException: Failed to unregister dubbo://169.254.76.30:29999/com.linda.scheduler.api.remote.ScheduleApiExecutor?anyhost=true&application=aidaojia_test&dubbo=2.5.3&group=aidaojia&interface=com.linda.scheduler.api.remote.ScheduleApiExecutor&methods=executeTask&pid=8000&revision=1.0.0_test&side=provider&timestamp=1456745605949&version=1.0.0_test to zookeeper zookeeper://192.168.2.211:2181/com.alibaba.dubbo.registry.RegistryService?application=aidaojia_test&dubbo=2.5.3&interface=com.alibaba.dubbo.registry.RegistryService&pid=8000&timestamp=1456745605009, cause: null
    at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doUnregister(ZookeeperRegistry.java:110)
    at com.alibaba.dubbo.registry.support.FailbackRegistry.unregister(FailbackRegistry.java:160)
    ... 11 more
Caused by: java.lang.NullPointerException
    at org.I0Itec.zkclient.ZkClient$8.call(ZkClient.java:720)
    at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:675)
    at org.I0Itec.zkclient.ZkClient.delete(ZkClient.java:716)
    at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperClient.delete(ZkclientZookeeperClient.java:57)
    at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doUnregister(ZookeeperRegistry.java:108)
```

**Comment by zhangxd1989** [comment]
遇到了同样的问题,您解决了吗?

**Comment by wang7x** [comment]
遇到同样的问题,请问有人解决了吗?

**Comment by zhangxd1989** [comment]
我使用 spring boot + dubbo 的时候会出现这个问题, 使用 spring + dubbo 就没有这个问题, 我对比了两个的差异,发现 spring boot 启动的时候会注册 shutdownhook,当关闭的时候会调用这个钩子把 spring 容器管理的 Bean 销毁, 我设置了 application.setRegisterShutdownHook(false); 后 就不会再报这个异常了.

**Comment by whx4J8** [comment]
是不是注册中心的链接已经被释放了？

**Comment by whx4J8** [comment]
@zhangxd1989 麻烦问下你怎么设置的application.setRegisterShutdownHook(false);
谢谢

**Comment by L316476844** [comment]
@zhangxd1989 请教一下如何设置application.setRegisterShutdownHook(false);

**Comment by zhangxd1989** [comment]
@L316476844 如果你指的是 spring boot 的话，在入口处设置就好了
```
@SpringBootApplication
public class ProviderApplication {

    public static void main(String[] args) throws IOException {
        SpringApplication application = new SpringApplication(ProviderApplication.class);
        application.setRegisterShutdownHook(false);
        application.run(args);
    }
}
```

**Comment by L316476844** [comment]
@zhangxd1989 我使用的是spring boot 项目正常启动关闭没有问题，测试用例有这种问题java.lang.IllegalStateException: Failed to unregister dubbo://192.168.53.252:27888/

**Comment by chigend** [comment]
@zhangxd1989 如果不是springboot，是jetty启动的启用该如何取消设置shutdownhook呢？
