### ISSUE TITLE
zookeeper一直出现大量连接断开

### ISSUE THREAD

**Issue by quyangg** [alibaba/dubbo#346]
2016-11-22 09:14:42,887 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /192.168.192.11:33353 (no session established for client)
2016-11-22 09:15:42,989 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /192.168.192.11:33412
2016-11-22 09:15:42,990 - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
        at java.lang.Thread.run(Thread.java:745)
2016-11-22 09:15:42,990 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /192.168.192.11:33412 (no session established for client)
2016-11-22 09:16:42,987 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /192.168.192.11:33473
2016-11-22 09:16:42,988 - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
        at java.lang.Thread.run(Thread.java:745)
2016-11-22 09:16:42,988 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /192.168.192.11:33473 (no session established for client)
2016-11-22 09:17:42,965 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /192.168.192.11:33522
2016-11-22 09:17:42,966 - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
        at java.lang.Thread.run(Thread.java:745)
2016-11-22 09:17:42,966 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /192.168.192.11:33522 (no session established for client)
2016-11-22 09:18:43,005 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /192.168.192.11:33573
2016-11-22 09:18:43,005 - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
        at java.lang.Thread.run(Thread.java:745)
2016-11-22 09:18:43,006 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /192.168.192.11:33573 (no session established for client)
2016-11-22 09:19:43,063 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /192.168.192.11:33621
2016-11-22 09:19:43,064 - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
        at java.lang.Thread.run(Thread.java:745)
2016-11-22 09:19:43,065 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /192.168.192.11:33621 (no session established for client)
2016-11-22 09:20:43,390 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /192.168.192.11:33670
2016-11-22 09:20:43,390 - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
        at java.lang.Thread.run(Thread.java:745)
2016-11-22 09:20:43,391 - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /192.168.192.11:33670 (no session established for client)

**Comment by quyangg** [comment]
I don't know the problem.Who knows how to solve it? thanks

**Comment by tixo** [comment]
"likely client has closed socket"
check your network, such as firewall ...

**Comment by 356082462** [comment]
重启你的客户端程序。

**Comment by quyangg** [comment]
@356082462  我重启了很多遍服务 没用  请问怎么重启客户端？

**Comment by quyangg** [comment]
@tixo  I have shut down the firewall
`[root@hadoop001 man1]# service   iptables status
iptables：未运行防火墙。
You have new mail in /var/spool/mail/root`

**Comment by hsming** [comment]
`sessionid 0x0` means client can not connect to the server, possible reason is network unreachable(you can use `telnet $ip $port ` to check), or connect timeout for zkclient is too short(you can change the zkclient connect timeout to a larger time).

**Comment by gosenme** [comment]
这个问题最终没人知道什么原因吗？看见很多论坛都有提到这个错。

**Comment by hsming** [comment]
`sessionid 0x0`说明客户端没有连上zookeeper，需要检查配置是否正确、网络是否通、有无防火墙等等。 如果确认这些都没有问题那应该就是服务端拒掉了连接，需要查看一下zookeeper服务端日志来确定原因，比如说可能是安全认证没有配置正确、客户端时间和服务端时间相差太大等等

**Comment by gosenme** [comment]
我们也遇到过类似问题, 我们尝试了各种方法.都没法解决.  我怀疑是tomcat的问题. 出现这个问题的时候tomcat的catalina.out日志也在对应的刷. tomcat   ./shutdown.sh 之后还是有问题. 直接Kill -9  tomcat_pid  ,然后再重启客户端服务的话就OK   ,所以之后我们果断不用war包了,改成jar  . 至今这个问题没有再出现.

**Comment by zhaoxilingcheng** [comment]
这个问题两个月以前，遇到过，然后改了本地ip就好了。

**Comment by huairen** [comment]
原因是timeout设置时间太短，导致在验证时写入超时，所以要检查一下connect接口上的timeout，记得*time.Second

**Comment by machelcheng** [comment]
> 原因是timeout设置时间太短，导致在验证时写入超时，所以要检查一下connect接口上的timeout，记得*time.Second
hi，这个timeout设置为多少合适呢？

**Comment by zhaoxilingcheng** [comment]
看你的业务逻辑处理是个长处理还是？一般接口3~5秒可以了



------------------ 原始邮件 ------------------
发件人: "machelcheng"<notifications@github.com>; 
发送时间: 2019年9月18日(星期三) 晚上10:48
收件人: "apache/dubbo"<dubbo@noreply.github.com>; 
抄送: "得不到"<308870555@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [apache/dubbo] zookeeper一直出现大量连接断开 (#346)



 
原因是timeout设置时间太短，导致在验证时写入超时，所以要检查一下connect接口上的timeout，记得*time.Second
 hi，这个timeout设置为多少合适呢？

**Comment by machelcheng** [comment]
> 原因是timeout设置时间太短，导致在验证时写入超时，所以要检查一下connect接口上的timeout，记得*time.Second

这个不行， 将connect的timeout改大了*time.Second，还是一直刷这个错误
