### ISSUE TITLE
Not found exported service

### ISSUE THREAD

**Issue by modowei** [alibaba/dubbo#439]
resin+dubbo 停机时报：

`[2017-05-04 14:04:38.442](14:04:38.442 [New I/O worker #7]) INFO  c.a.d.r.p.d.CallbackServiceCodec 50 -  [DUBBO] Not found exported service com.xxxxxxxxxxxxxxx`

发现在之前spring已经有这样的destroy：
`[2017-05-04 14:04:38.103](14:04:38.103 [resin-destroy]) INFO  o.s.b.f.s.DefaultListableBeanFactory 444 - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@7f0ab78a: defining beans [...........com.xxxxxxxxxxxxxxx]`

用另外一个ContextLoaderListener方式先销毁dubbo，再销毁spring容器：
`@Override
	public void contextDestroyed(ServletContextEvent event) {
		ProtocolConfig.destroyAll();
		super.contextDestroyed(event);
	}`

由于ServiceBean会实现了destroy()方法，unregister会执行有两次，第二次会报：
`[2017-05-04 12:19:04.821]java.lang.IllegalStateException: Failed to unregister dubbo://....................., cause: ZkClient already closed!
[2017-05-04 12:19:04.821]       at com.alibaba.dubbo.registry.support.FailbackRegistry.unregister(FailbackRegistry.java:173) ~[FailbackRegistry.class:2.5.4-SNAPSHOT]
[2017-05-04 12:19:04.821]       at com.alibaba.dubbo.registry.integration.RegistryProtocol$1.unexport(RegistryProtocol.java:130) ~[RegistryProtocol$1.class:2.5.4-SNAPSHOT]
[2017-05-04 12:19:04.821]       at com.alibaba.dubbo.config.ServiceConfig.unexport(ServiceConfig.java:270) [ServiceConfig.class:2.5.4-SNAPSHOT]
[2017-05-04 12:19:04.821]       at com.alibaba.dubbo.config.spring.ServiceBean.destroy(ServiceBean.java:255) [ServiceBean.class:2.5.4-SNAPSHOT]
[2017-05-04 12:19:04.821]       at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:239) [DisposableBeanAdapter.class:3.2.16.RELEASE]
[2017-05-04 12:19:04.821]       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:510) [DefaultSingletonBeanRegistry.class:3.2.16.RELEASE]
[2017-05-04 12:19:04.821]       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:486) [DefaultSingletonBeanRegistry.class:3.2.16.RELEASE]
[2017-05-04 12:19:04.821]       at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:751) [DefaultListableBeanFactory.class:3.2.16.RELEASE]
[2017-05-04 12:19:04.821]       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:455) [DefaultSingletonBeanRegistry.class:3.2.16.RELEASE]
[2017-05-04 12:19:04.821]       at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1096) [AbstractApplicationContext.class:3.2.16.RELEASE]
[2017-05-04 12:19:04.821]       at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1070) [AbstractApplicationContext.class:3.2.16.RELEASE]
[2017-05-04 12:19:04.821]       at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1016) [AbstractApplicationContext.class:3.2.16.RELEASE]
[2017-05-04 12:19:04.821]       at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:586) [ContextLoader.class:3.2.16.RELEASE]
[2017-05-04 12:19:04.821]       at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:143) [ContextLoaderListener.class:3.2.16.RELEASE]
[2017-05-04 12:19:04.821]       at com.zongheng.service.book.DubboContextLoaderListener.contextDestroyed(DubboContextLoaderListener.java:15) [classes:na]
[2017-05-04 12:19:04.821]       at com.caucho.server.webapp.WebApp.stop(WebApp.java:2773) [resin.jar:3.1.0]`

大家有没有别的好的方法？

**Comment by chickenlj** [comment]
spring的bean销毁线程：ServiceBean.destroy（）
与
dubboshutdownhook线程: AbstractConfig中的ProtocolConfig.destroyAll();

并发执行导致

**Comment by wuwen5** [comment]
参考 #333 .

我们这边的做法是由自动部署系统触发一个停机消息，然后应用主动调用销毁方法进行优雅停机的。

大致步骤为
```java
//1.开始断开注册中心连接
AbstractRegistryFactory.destroyAll();

//2.连接检测
...

//3.销毁dubbo protocol
static void destroyProtocol() {
        ExtensionLoader<Protocol> loader = ExtensionLoader.getExtensionLoader(Protocol.class);
        for (String protocolName : loader.getLoadedExtensions()) {
            try {
                Protocol protocol = loader.getLoadedExtension(protocolName);
                if (protocol != null) {
                    protocol.destroy();
                }
            } catch (Exception t) {
                LOGGER.warn("调用dubbo Protocol.destroy 失败.", t);
            }
        }
    }

//4.-销毁dubbo protocol结束, 开始释放 NettyClientChannelFactory
/**
     * 销毁netty client的线程资源.
     * */
    static void destroyNetty() throws NoSuchFieldException {
        final Field field = NettyClient.class.getDeclaredField("channelFactory");

        AccessController.doPrivileged(new PrivilegedAction<Object>() {

            @Override
            public Object run() {
                field.setAccessible(true);
                ChannelFactory channelFactory;
                try {
                    channelFactory = (ChannelFactory) field.get(NettyClient.class);
                    channelFactory.shutdown();
                } catch (IllegalAccessException e) {
                    LOGGER.info("销毁netty client线程资源失败.", e);
                }
                return null;
            }
        });
    }
```
