### ISSUE TITLE
dubbo admin控制台禁用服务无效，点击禁用后仍能使用服务

### ISSUE THREAD

**Issue by Paul0523** [alibaba/dubbo#567]
用断点跟了下发现是虽然comsumer收到节点更新事件了，但是最终因为newUrlInvokerMap.size 等于0导致没有更新urlInvokerMap，这个是bug吗？

**Comment by DocEcho** [comment]
只剩一个 provider 了，就不能禁用了把

**Comment by chickenlj** [comment]
禁用后导致无可用provider的规则不会生效

**Comment by Paul0523** [comment]
@DocEcho @chickenlj 谢谢了，明白了。

**Comment by gMan1990** [comment]
@chickenlj 禁用会不会影响服务的响应？比如服务已经有请求进来在处理了，然后禁用一下，那这个请求会得到响应么？
我还看到禁用后有个报错的。
`WARN  alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable (ChannelEventRunnable.java:84) -  [DUBBO] ChannelEventRunnable handle RECEIVED operation error, channel is NettyChannel [channel=[id: 0xbe7b109e, /72.0.253.61:34325 :> /72.0.253.62:20884]], message is Request [id=5143154, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=projectRepay, parameterTypes=[class com.lianpay.trusteebusi.v2.service.dto.ProRepayReqBean], arguments=[com.lianpay.trusteebusi.v2.service.dto.ProRepayReqBean@1143808c], attachments={dubbo=2.5.3, input=901, path=com.lianpay.trusteebusi.v2.service.IProjectRepayManage, interface=com.lianpay.trusteebusi.v2.service.IProjectRepayManage, timeout=35000, version=0.0.0}]], dubbo version: 2.5.3, current host: 72.0.253.62
com.alibaba.dubbo.remoting.RemotingException: Failed to send message Response [id=5143154, version=2.0.0, status=20, event=false, error=null, result=RpcResult [result=com.lianpay.trusteebusi.v2.service.dto.ProRepayRspBean@7fc949a3, exception=null]] to /72.0.253.61:34325, cause: null
        at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:108)
        at com.alibaba.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:51)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:171)
        at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
        at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:434)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:129)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
        at org.jboss.netty.channel.Channels.write(Channels.java:725)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)`
