### ISSUE TITLE
javassist新版本兼容性的问题

### ISSUE THREAD

**Issue by chickenlj** [alibaba/dubbo#627]
接口定义如下：
`public interface MouseService {
    void eat();

    void getName(); //怀疑是getXxx方法有问题 name()或getName(String a)等形式都可以
}
`
Jdk版本1.8， javassist版本3.20.0-GA版本时报以下异常，javassist版本3.15.0运行正常（但不支持jdk1.8特性）：

`java.lang.RuntimeException: [source error] getPropertyValue (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object; in com.alibaba.dubbo.common.bytecode.Wrapper0: inconsistent stack height -1
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:302) ~[dubbo-2.5.4.jar:2.5.4]
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:256) ~[dubbo-2.5.4.jar:2.5.4]
	at com.alibaba.dubbo.common.bytecode.Wrapper.makeWrapper(Wrapper.java:239) ~[dubbo-2.5.4.jar:2.5.4]
	at com.alibaba.dubbo.common.bytecode.Wrapper.getWrapper(Wrapper.java:101) ~[dubbo-2.5.4.jar:2.5.4]
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:492) ~[dubbo-2.5.4.jar:2.5.4]
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:346) ~[dubbo-2.5.4.jar:2.5.4]
	at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:307) ~[dubbo-2.5.4.jar:2.5.4]
	at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:206) ~[dubbo-2.5.4.jar:2.5.4]
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:109) ~[dubbo-2.5.4.jar:2.5.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at com.alibaba.dubbo.test.DubboFeatureTestApplication.main(DubboFeatureTestApplication.java:10) [classes/:na]
Caused by: javassist.CannotCompileException: [source error] getPropertyValue (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object; in com.alibaba.dubbo.common.bytecode.Wrapper0: inconsistent stack height -1
	at javassist.CtNewMethod.make(CtNewMethod.java:79) ~[javassist-3.20.0-GA.jar:na]
	at javassist.CtNewMethod.make(CtNewMethod.java:45) ~[javassist-3.20.0-GA.jar:na]
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:281) ~[dubbo-2.5.4.jar:2.5.4]
	... 22 common frames omitted
Caused by: javassist.compiler.CompileError: getPropertyValue (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object; in com.alibaba.dubbo.common.bytecode.Wrapper0: inconsistent stack height -1
	at javassist.compiler.Javac.compile(Javac.java:104) ~[javassist-3.20.0-GA.jar:na]
	at javassist.CtNewMethod.make(CtNewMethod.java:74) ~[javassist-3.20.0-GA.jar:na]
	... 24 common frames omitted`

**Comment by chickenlj** [comment]
void getName()的返回类型void不符合规范，javassist 3.15.0后必须是类似String getName()这种才可以

**Comment by dev4java** [comment]
Compile error. #1101

**Comment by revolyw** [comment]
不符合什么规范？
