### ISSUE TITLE
admin缺失applicationContext.xml文件

### ISSUE THREAD

**Issue by B0B02333** [alibaba/dubbo#636]
2.5.5编译后出现异常
ERROR context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from ServletContext resource [/WEB-INF/applicationContext.xml]; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/applicationContext.xml]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:344)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)

**Comment by chickenlj** [comment]
你编译的2.5.5是在tag拉的源码编译的吗？除了修复兼容问题这个版本是和2.5.4保持一致的，dubbo-admin建议从master直接拉取

**Comment by B0B02333** [comment]
我是直接下载的

**Comment by B0B02333** [comment]
2.5.4的admin我是没问题的

**Comment by chickenlj** [comment]
master最新代码已解决此问题，我把问题关掉了
