### ISSUE TITLE
dubbo接口报错，具体是什么原因造成的。

### ISSUE THREAD

**Issue by linchengkuan** [alibaba/dubbo#644]
调dubbo时报如下错误，一直没定位到问题，希望求解答。

```java
com.alibaba.dubbo.rpc.RpcException: Failfast invoke providers dubbo RandomLoadBalance select from all providers [com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegete@42f5ebb1, com.alibaba.dubbo.registry.integration.RegistryDirectory$InvokerDelegete@1f44d3cf] for service [] method [] on consumer HOST use dubbo version 2.4.9, but no luck to perform the invocation. Last error is: null
	at com.alibaba.dubbo.rpc.cluster.support.FailfastClusterInvoker.doInvoke(FailfastClusterInvoker.java:52) ~[dubbo-2.4.9.jar:2.4.9]
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:226) ~[dubbo-2.4.9.jar:2.4.9]
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72) ~[dubbo-2.4.9.jar:2.4.9]
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) ~[dubbo-2.4.9.jar:2.4.9]
	at com.alibaba.dubbo.common.bytecode.proxy5.sendMessage(proxy5.java) ~[na:2.4.9]
	at com.jiedaibao.paygent.biz.service.log.impl.WarningLogServiceImpl.sendWarningLog(WarningLogServiceImpl.java:118) ~[paygent-biz-1.0.jar:na]
	at com.jiedaibao.paygent.biz.service.log.impl.WarningLogServiceImpl$WarningLogSendRunnable.run(WarningLogServiceImpl.java:69) [paygent-biz-1.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
```

**Comment by goal578** [comment]
检查配置，应该是你的dubbo集群配置没配对

**Comment by chickenlj** [comment]
使用问题，请移步gitter讨论
https://gitter.im/alibaba/dubbo
