### ISSUE TITLE
dubbo_admin启动报错

### ISSUE THREAD

**Issue by missence** [alibaba/dubbo#670]
ERROR context.ContextLoader - Context initialization failed
java.lang.IllegalArgumentException: Could not include schema "../wsdl/http-conf.xsd" in cxf.apache.org/schemas/configuration/http-conf.xsd
	at com.alibaba.citrus.util.Assert$ExceptionType$1.newInstance(Assert.java:207)
	at com.alibaba.citrus.util.Assert.assertNotNull(Assert.java:85)
	at com.alibaba.citrus.util.Assert.assertNotNull(Assert.java:75)
	at com.alibaba.citrus.springext.support.SchemaSet.findIncludedSchema(SchemaSet.java:186)
	at com.alibaba.citrus.springext.support.SchemaSet.getAllIncludesDepthFirst(SchemaSet.java:177)
	at com.alibaba.citrus.springext.support.SchemaSet.getAllIncludes(SchemaSet.java:170)
	at com.alibaba.citrus.springext.support.SchemaSet.processIncludes(SchemaSet.java:99)
	at com.alibaba.citrus.springext.support.SchemaSet.<init>(SchemaSet.java:74)
	at com.alibaba.citrus.springext.support.resolver.SchemaEntityResolver.<init>(SchemaEntityResolver.java:38)
	at com.alibaba.citrus.springext.support.resolver.XmlBeanDefinitionReaderProcessor.addConfigurationPointsSupport(XmlBeanDefinitionReaderProcessor.java:88)
	at com.alibaba.citrus.springext.support.context.XmlWebApplicationContext.initBeanDefinitionReader(XmlWebApplicationContext.java:86)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:93)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:542)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:451)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at com.alibaba.citrus.webx.context.WebxComponentsLoader.initWebApplicationContext(WebxComponentsLoader.java:117)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by chickenlj** [comment]
用的什么版本的dubbo-admin那，就是原始代码启动报的错吗？
