### ISSUE TITLE
Monitor超时阻塞

### ISSUE THREAD

**Issue by timqq** [alibaba/dubbo#672]
Monitor超时阻塞 如果和zk连接失败会一直阻塞 导致dubbo工作线程不能处理请求

"http-bio-10001-exec-7" #66 daemon prio=5 os_prio=0 tid=0x00007faf04286800 nid=0x7c13 waiting on condition [0x00007faed05f1000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000ef7ca268> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:256)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitUntil(AbstractQueuedSynchronizer.java:2120)
	at org.I0Itec.zkclient.ZkClient.waitForKeeperState(ZkClient.java:636)
	at org.I0Itec.zkclient.ZkClient.waitUntilConnected(ZkClient.java:619)
	at org.I0Itec.zkclient.ZkClient.waitUntilConnected(ZkClient.java:615)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:679)
	at org.I0Itec.zkclient.ZkClient.create(ZkClient.java:304)
	at org.I0Itec.zkclient.ZkClient.createPersistent(ZkClient.java:213)
	at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperClient.createPersistent(ZkclientZookeeperClient.java:47)
	at com.alibaba.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:44)
	at com.alibaba.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:39)
	at com.alibaba.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:39)
	at com.alibaba.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:39)
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doRegister(ZookeeperRegistry.java:98)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:130)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:268)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:254)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:63)
	at com.alibaba.dubbo.rpc.Protocol$Adpative.refer(Protocol$Adpative.java)
	at com.alibaba.dubbo.monitor.dubbo.DubboMonitorFactroy.createMonitor(DubboMonitorFactroy.java:60)
	at com.alibaba.dubbo.monitor.support.AbstractMonitorFactory.getMonitor(AbstractMonitorFactory.java:56)

**Comment by chickenlj** [comment]
是存在阻塞请求的情况

**Comment by zhangguanzhang** [comment]
楼主这个问题解决了吗 @timqq

**Comment by zhangguanzhang** [comment]
解决了，找默然大佬解决的
