### ISSUE TITLE
dubbo偶发性的空指针问题，出现之后可以作为服务方但是不能作为消费方

### ISSUE THREAD

**Issue by yangpancode** [alibaba/dubbo#687]
dubbo偶发性的空指针问题，问题的出现很偶然，可能一周一两次，影响范围只在单台服务器，出现问题之后，该服务可以作为dubbo服务提供方可以对外正常提供服务，但是作为dubbo消费方，无法调用外部服务（所有接口都无法调用），均出现如下空指针异常，重启之后一切又恢复正常。更加诡异的是DefaultFuture.java的34行代码是import com.alibaba.dubbo.remoting.exchange.Response。
java.lang.NullPointerException: null
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:34) ~[dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:90) ~[dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:104) [dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144) [dubbo-2.8.3.jar:2.8.3]
	at com.hf.framework.filter.TraceFilter.invoke(TraceFilter.java:54) [share-log-0.0.5-SNAPSHOT.jar:na]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53) [dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) [dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48) [dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74) [dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) [dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77) [dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227) [dubbo-2.8.3.jar:2.8.3]
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72) [dubbo-2.8.3.jar:2.8.3]

**Comment by chickenlj** [comment]
#532

**Comment by qinliujie** [comment]
#532 已处理
