### ISSUE TITLE
dubbo-admin-2.5.5版本的war包放到Tomcat webapps下，启动时报错

### ISSUE THREAD

**Issue by lingyanwang12** [alibaba/dubbo#735]
INFO context.ContextLoader - Root WebApplicationContext: initialization started
 INFO support.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Thu Oct 12 16:58:43 CST 2017]; root of context hierarchy
 INFO xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/applicationContext.xml]
ERROR context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from ServletContext resource [/WEB-INF/applicationContext.xml]; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/applicationContext.xml]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:344)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)

**Comment by halober** [comment]
你打的war包，/WEB-INF/applicationContext.xml文件没有打进去。

**Comment by lingyanwang12** [comment]
我再项目里没找到有applicationContext.xml呢?

**Comment by halober** [comment]
看异常日志啊，dubbo-admin里边的

**Comment by chickenlj** [comment]
@lingyanwang12  使用3.x及以下版本的spring

**Comment by halober** [comment]
dubbo-admin,还没有支持4.0

**Comment by lingyanwang12** [comment]
改成3.2的版本就好了，谢谢。
