### ISSUE TITLE
服务提供方程序启动报No such extension错误

### ISSUE THREAD

**Issue by matthew-he** [alibaba/dubbo#760]
在SpringBoot里按注解配置dubbo，服务提供方程序一启动就报错：
Caused by: java.lang.IllegalStateException: No such extension com.alibaba.dubbo.remoting.Codec by name dubbo1compatible
	at com.alibaba.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:489) ~[dubbo-2.5.6.jar:2.5.6]
	at com.alibaba.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:496) ~[dubbo-2.5.6.jar:2.5.6]
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:317) ~[dubbo-2.5.6.jar:2.5.6]
	at com.alibaba.dubbo.remoting.transport.AbstractEndpoint.getChannelCodec(AbstractEndpoint.java:56) ~[dubbo-2.5.6.jar:2.5.6]
这是怎么回事呢？

**Comment by chickenlj** [comment]
检查classpath是否有此类：com/taobao/remoting/impl/ConnectionRequest.class。
我们会在2.5.7版本去掉此判断逻辑

**Comment by Qinbaobo** [comment]
这个再不升级的时候该怎么去解决呢？
