### ISSUE TITLE
2.5.6使用redis作为注册中心报错

### ISSUE THREAD

**Issue by wzlee** [alibaba/dubbo#772]
```java
2017-10-25 15:17:08.667  WARN 53478 --- [eTimer-thread-1] c.a.dubbo.registry.redis.RedisRegistry   :  [DUBBO] Failed to write provider heartbeat to redis registry. registry: 127.0.0.1:6379, cause: Could not get a resource from the pool, dubbo version: 2.5.6, current host: 127.0.0.1

redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:51) ~[jedis-2.9.0.jar:na]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226) ~[jedis-2.9.0.jar:na]
	at com.alibaba.dubbo.registry.redis.RedisRegistry.deferExpired(RedisRegistry.java:161) [dubbo-2.5.6.jar:2.5.6]
	at com.alibaba.dubbo.registry.redis.RedisRegistry.access$000(RedisRegistry.java:56) [dubbo-2.5.6.jar:2.5.6]
	at com.alibaba.dubbo.registry.redis.RedisRegistry$1.run(RedisRegistry.java:149) [dubbo-2.5.6.jar:2.5.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
Caused by: java.util.NoSuchElementException: Unable to validate object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:506) ~[commons-pool2-2.4.2.jar:2.4.2]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363) ~[commons-pool2-2.4.2.jar:2.4.2]
	at redis.clients.util.Pool.getResource(Pool.java:49) ~[jedis-2.9.0.jar:na]
	... 11 common frames omitted

**Comment by wzlee** [comment]
已解决，redis密码不支持的问题。已pull requset至dubbo

**Comment by qqyyaa** [comment]
@wzlee  好像没pull 成功，

**Comment by chickenlj** [comment]
@wzlee thx 计划在2.5.8版本处理你的PR
