### ISSUE TITLE
zk框架抛出Watcher exception Path cannot be null

### ISSUE THREAD

**Issue by fuxiaojing** [alibaba/dubbo#803]
`2017-11-01 20:14:24,875 | ERROR | main-EventThread | CuratorFrameworkImpl.java:566 | - Watcher exception
java.lang.IllegalArgumentException: Path cannot be null
    at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:48)
    at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:37)
    at org.apache.curator.utils.ZKPaths.fixForNamespace(ZKPaths.java:105)
    at org.apache.curator.framework.imps.NamespaceImpl.fixForNamespace(NamespaceImpl.java:104)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.fixForNamespace(CuratorFrameworkImpl.java:594)
    at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:198)
    at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:40)
    at com.alibaba.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient$CuratorWatcherImpl.process(CuratorZookeeperClient.java:150)
    at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:68)
    at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522)
    at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
`
异常栈如上，这应该是传给zk forPath 方法一个不存在的path,  能否在dubbo 框架层做拦截，并打印出哪个path 绑定的listener 出现了异常，这个是与zk 连接出现异常时抛出的， 还有 哪些情况下会产生这种异常？

**Comment by qinliujie** [comment]
用的是哪个版本的 curator 呢？ @fuxiaojing

**Comment by jy00278439** [comment]
请问问题解决了嘛？@fuxiaojing

**Comment by wangyixiaohuihui** [comment]
请问这个问题解决了吗?

**Comment by seedily** [comment]
看到新版的dubbo，CuratorZookeeperClient类有针对null Path的场景，会对null path处理一下。

好明显，这样改动是可以避免这个报错，到时没说明白为什么要这样修改

**Comment by zonghaishang** [comment]
The source code has more detail reason.

诣极

在 2018年3月14日，17:29，Liu Weijian <notifications@github.com<mailto:notifications@github.com>> 写道：


看到新版的dubbo，CuratorZookeeperClient类有针对null Path的场景，会对null path处理一下。

好明显，这样改动是可以避免这个报错，到时没说明白为什么要这样修改

**Comment by mmxf** [comment]
这个问题怎么解决

**Comment by AllenSun23** [comment]
怎么解决的

**Comment by mmxf** [comment]
我们是换个ip就好了
