### ISSUE TITLE
dubbo monitor 异常：Can not lock the registry cache file

### ISSUE THREAD

**Issue by liguoxijob** [alibaba/dubbo#806]
```
2017-11-01  15:40:32.070 [DubboSaveRegistryCache-thread-1hread] com.alibaba.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:221)evel com.alibaba.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:221)ogger{80} 221 -  [DUBBO] Failed to save registry store file, cause: Can not lock the registry cache file /home/admin/.dubbo/dubbo-registry-mt-zookeeper-vip.cache, ignore and retry later, maybe multi java process use the file, please config: dubbo.registry.file=xxx.properties, dubbo version: 3.8.7, current host: 10.7.13.46sg
java.io.IOException: Can not lock the registry cache file /home/admin/.dubbo/dubbo-registry-mt-zookeeper-vip.cache, ignore and retry later, maybe multi java process use the file, please config: ### dubbo.registry.file=xxx.properties
        at com.alibaba.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:193)
        at 

com.alibaba.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:150)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
```
dubbo monitor遇到这种问题该如何解决？错误信息提示配置：dubbo.registry.file=xxx.properties，但是我本地试了之后不起效果。

**Comment by chickenlj** [comment]
这个日志一般不影响正常业务使用
同机器部署多个dubbo应用，通过[dubbo.registry.file](https://dubbo.gitbooks.io/dubbo-user-book/content/references/xml/dubbo-registry.html)分别配置注册中心缓存文件保存到不同位置

**Comment by liguoxijob** [comment]
我服务器安装dubbo-monitor监控平台后，日志文件一直报这样的异常，请问可以屏蔽这样的日志信息吗？？？

**Comment by yekui** [comment]
2018-10-15 22:55:24,780 WARN [DubboSaveRegistryCache-thread-1] c.a.d.c.u.DubboLogger -  [DUBBO] Failed to save registry store file, cause: null, dubbo version: 3.2.0, current host: xxx
java.nio.channels.OverlappingFileLockException: null
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at com.alibaba.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:187)
	at com.alibaba.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:146)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

这个应该不是多进程并发导致的吧
