### ISSUE TITLE
linux中jdk 1.8 中部署dubbo-admin-2.5.7 出现如下错误

### ISSUE THREAD

**Issue by caiqiufang** [alibaba/dubbo#842]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.citrus.service.velocity.impl.VelocityEngineImpl#6aecc22d': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.alibaba.citrus.service.velocity.impl.VelocityEngineImpl]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/collections/ExtendedProperties
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1039)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:985)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:276)
        ... 31 more
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.alibaba.citrus.service.velocity.impl.VelocityEngineImpl]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/collections/ExtendedProperties
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1032)
        ... 35 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections/ExtendedProperties
        at org.apache.velocity.runtime.RuntimeInstance.<init>(RuntimeInstance.java:183)
        at com.alibaba.citrus.service.velocity.impl.VelocityRuntimeInstance.<init>(VelocityRuntimeInstance.java:52)
        at com.alibaba.citrus.service.velocity.impl.VelocityEngineImpl.<init>(VelocityEngineImpl.java:62)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
        ... 37 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.ExtendedProperties
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
        ... 45 more

**Comment by caiqiufang** [comment]
maven jar 包未加载完全
