### ISSUE TITLE
时不时会有这个异常java.lang.RuntimeException: java.lang.InterruptedException

### ISSUE THREAD

**Issue by ybqiang** [alibaba/dubbo#846]
java.lang.RuntimeException: java.lang.InterruptedException
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:102) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:96) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.common.bytecode.proxy0.albumVideos(proxy0.java) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]

**Comment by ybqiang** [comment]
补充下：
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2017) ~[na:1.7.0_45]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2188) ~[na:1.7.0_45]
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:96) ~[dubbo-2.5.4.jar:2.5.4-SNAPSHOT]

**Comment by chickenlj** [comment]
消费端线程等待结果返回时被interrupt了，**请先检查一下是否有对业务线程的主动interrupt操作**
另外，建议升级dubbo到2.5.7版本，2.5.4版本有很多问题已经修复
