### ISSUE TITLE
启动一直警告：ChannelEventRunnable handle RECEIVED operation error

### ISSUE THREAD

**Issue by hungki** [alibaba/dubbo#849]
一、服务端报错：
17-11-13.18:30:06.955 [DubboServerHandler-172.16.60.33:20885-thread-199] WARN  ChannelEventRunnable    -  [DUBBO] ChannelEventRunnable handle RECEIVED operation error, channel is NettyChannel [channel=[id: 0x193d6877, /127.0.0.1:33106 :> /127.0.0.1:20885]], message is status, dubbo version: 2.4.9, current host: 127.0.0.1
com.alibaba.dubbo.remoting.RemotingException: Failed to send message OK
dubbo> to /127.0.0.1:33106, cause: null
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:108) ~[dubbo-2.4.9.jar:2.4.9]
	at com.alibaba.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:51) ~[dubbo-2.4.9.jar:2.4.9]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:185) ~[dubbo-2.4.9.jar:2.4.9]
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52) ~[dubbo-2.4.9.jar:2.4.9]
	at com.alibaba.dubbo.remoting.transport.dispather.ChannelEventRunnable.run(ChannelEventRunnable.java:82) ~[dubbo-2.4.9.jar:2.4.9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
Caused by: java.nio.channels.ClosedChannelException: null
	at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:643) ~[netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:370) ~[netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137) ~[netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76) ~[netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.Channels.write(Channels.java:632) ~[netty-3.2.5.Final.jar:na]
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:70) ~[netty-3.2.5.Final.jar:na]
	at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:99) ~[dubbo-2.4.9.jar:2.4.9]
	at org.jboss.netty.channel.Channels.write(Channels.java:611) ~[netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.Channels.write(Channels.java:578) ~[netty-3.2.5.Final.jar:na]
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:251) ~[netty-3.2.5.Final.jar:na]
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:98) ~[dubbo-2.4.9.jar:2.4.9]
	... 7 common frames omitted
二、消费者报错：
Failed to invoke method set, cause: com.alibaba.dubbo.rpc.RpcException: Invalid token! Forbid invoke remote service interface com.rrkd.redis.rpc.ICacheRpcService method set() from consumer 192.168.122.1 to provider 172.16.60.33
com.alibaba.dubbo.rpc.RpcException: Invalid token! Forbid invoke remote service interface com.rrkd.redis.rpc.ICacheRpcService method set() from consumer 192.168.122.1 to provider 172.16.60.33
	at com.alibaba.dubbo.rpc.filter.TokenFilter.invoke(TokenFilter.java:46)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.telnet.InvokeTelnetHandler.telnet(InvokeTelnetHandler.java:98)
	at com.alibaba.dubbo.remoting.telnet.support.TelnetHandlerAdapter.telnet(TelnetHandlerAdapter.java:56)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:183)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispather.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
三、配置：
dubbo.protocol.name=dubbo
dubbo.protocol.port=20885
dubbo.protocol.host=0.0.0.0

问题：本机上没有消费者，服务端启动一直报WARN，使用telnet 127.0.0.1 20885 可以进入dubbo远程调用，测试调用消费者报错。求大神。

**Comment by chickenlj** [comment]
你的服务是不是开启了token验证，消费端可能使用方式有误，请参考使用手册`令牌验证 `章节确认一下

**Comment by chickenlj** [comment]
这应该是一个使用问题，我先关闭issue了，有问题可以继续在[gitter](https://gitter.im/alibaba/dubbo)或[google user group](https://groups.google.com/forum/#!forum/dubbo)交流
