### ISSUE TITLE
下断点以后 dubbo一直不停报错

### ISSUE THREAD

**Issue by teemoer** [alibaba/dubbo#914]
开发中在提供者或者消费者 下断点时间超过十秒到20秒钟 就会一直报错,不停地抛异常 

```

org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:198)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:488)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:199)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38)
	at com.alibaba.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient$CuratorWatcherImpl.process(CuratorZookeeperClient.java:119)
	at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:67)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)

```

有时候又会报 这个错误

```

java.lang.IllegalArgumentException: Path cannot be null
	at org.apache.zookeeper.common.PathUtils.validatePath(PathUtils.java:45)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1572)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:199)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38)
	at com.alibaba.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient$CuratorWatcherImpl.process(CuratorZookeeperClient.java:119)
	at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:67)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)

```

请问是什么原因呢?  
我已经把 
提供者和消费者端的 超时时间设置成了60秒了  还是不行 如果断点超过10-20秒钟左右 就会报错

  dubbox:
    scan: sx.java.gitlab  # dubbox 注解扫描包地址
    consumer:
      check: false # 不检查
      timeout: 60000   # 开发环境 60s
      retries: 1       # 重试次数 1

**Comment by takeseem** [comment]
看着像zk在重新建立连接，这个应该是正常的。你的是dubbox项目还是dubbo项目罗？

**Comment by teemoer** [comment]
@takeseem  是dubbox 项目  就是  有时候 我下断点 时间久一点再放开断点就会报这个错

**Comment by takeseem** [comment]
理论上，你可以在进入断点后，查看zk保持心跳的线程堆栈，找到其block在哪儿，对比你当前的线程，找到相交点就能定位到原因了。
如果是同一个线程，那肯定超时，如果不是同一个线程，是不是zk等待一个你当前线程持有的锁？

**Comment by teemoer** [comment]
@takeseem  不大熟悉ZK和Dubbox之间的联系   能力所限，希望能够修改一下配置文件就解决这个问题了  感谢你的回复，我先找点资料试试你说的方法，不过这样我解决问题的可能性很小。  再次感谢你提供的帮助。
