### ISSUE TITLE
2.5.7 @Reference 注解配置无法设定注册中心

### ISSUE THREAD

**Issue by roc-cn** [alibaba/dubbo#971]
2.5.7 中推荐 使用
@DubboComponentScan
方式开启Dubbo注解配置

这样会通过
ReferenceAnnotationBeanPostProcessor
来处理@Reference

但是 
ReferenceAnnotationBeanPostProcessor
会在Bean Field注入时，通过buildReferenceBean方法，去调用`com.alibaba.dubbo.config.spring.beans.factory.annotation.AbstractAnnotationConfigBeanBuilder#build`

而这个方法：
```
public final B build() throws Exception {

        checkDependencies();

        B bean = doBuild();

        configureBean(bean);

        if (logger.isInfoEnabled()) {
            logger.info(bean + " has been built.");
        }

        return bean;

    }
```
会输出bean的日志，从而触发ReferenceConfig的toString方法

ReferenceConfig的toString方法，会以此通过反射调用Bean的get方法
这就导致 `com.alibaba.dubbo.config.spring.ReferenceBean.getObject`方法被调用

以上的机制可能导致 在Spring MVC + Servlet 3.1 注解方式的场景下
通过`com.egege.mini.configuration.ServletInitializer#getRootConfigClasses`指定
```
@Configuration
@DubboComponentScan
public class DubboConfiguration {
 @Bean
    public ApplicationConfig applicationConfig(){
....
   }
@Bean
    public RegistryConfig registryConfig(){
....
}
}
```
此时
`com.alibaba.dubbo.config.spring.ReferenceBean#afterPropertiesSet`
无法获取RegistryConfig 

而这种情况下只能
```
@Reference(application = "applicationConfig", registry = "registryConfig")
    private PayService payCenter;
```
手工指定注解的registry属性

**Comment by roc-cn** [comment]
```
2017-11-29 23:09:58,799 DEBUG o.s.b.f.s.DefaultListableBeanFactory [localhost-startStop-1] Returning cached instance of singleton bean 'consumerConfig'
2017-11-29 23:09:58,799 DEBUG o.s.b.f.s.DefaultListableBeanFactory [localhost-startStop-1] Returning cached instance of singleton bean 'applicationConfig'
2017-11-29 23:09:58,839 WARN c.a.d.c.AbstractConfig [localhost-startStop-1]  [DUBBO] null, dubbo version: 2.5.7, current host: 10.161.139.95
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.alibaba.dubbo.config.AbstractConfig.toString(AbstractConfig.java:473) [dubbo-2.5.7.jar:2.5.7]
	at java.lang.String.valueOf(String.java:2994) [?:1.8.0_111]
	at java.lang.StringBuilder.append(StringBuilder.java:131) [?:1.8.0_111]
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.AbstractAnnotationConfigBeanBuilder.build(AbstractAnnotationConfigBeanBuilder.java:61) [dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.buildReferenceBean(ReferenceAnnotationBeanPostProcessor.java:328) [dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.access$200(ReferenceAnnotationBeanPostProcessor.java:44) [dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceFieldElement.inject(ReferenceAnnotationBeanPostProcessor.java:306) [dubbo-2.5.7.jar:2.5.7]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) [spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.postProcessPropertyValues(ReferenceAnnotationBeanPostProcessor.java:71) [dubbo-2.5.7.jar:2.5.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) [spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) [spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) [spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) [spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) [spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) [spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4725) [catalina.jar:8.5.6]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189) [catalina.jar:8.5.6]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403) [catalina.jar:8.5.6]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393) [catalina.jar:8.5.6]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalStateException: No such any registry to refer service in consumer 10.161.139.95 use dubbo version 2.5.7, Please add <dubbo:registry address="..." /> to your spring config. If you want unregister, please set <dubbo:service registry="N/A" />
	at com.alibaba.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:115) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.config.AbstractInterfaceConfig.loadRegistries(AbstractInterfaceConfig.java:155) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:375) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:332) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:161) ~[dubbo-2.5.7.jar:2.5.7]
	at com.alibaba.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:65) ~[dubbo-2.5.7.jar:2.5.7]
	... 35 more
```

**Comment by roc-cn** [comment]
原因应该是 #980 ，此问题关闭
