### ISSUE TITLE
problem with zookeeper+spring boot

### ISSUE THREAD

**Issue by yankai-victor** [alibaba/dubbo#989]
There is a problem in our system. We use zookeeper and spring boot. The protocal is dubbo protocal. After the service run for one or two days, this logcat comes out. At first we use zookeeper and spring mvc. And it works fine. 

```java
10:06:15 [New I/O server worker #1-3] WARN  o.j.n.channel.DefaultChannelPipeline -  [DUBBO] An exception was thrown by a user handler while handling an exception event ([id: 0x5f0f8a6d, /11.11.111.111:56890 => /11.11.11.111:41538] EXCEPTION: com.alibaba.dubbo.remoting.ExecutionException: class com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler error when process received event .), dubbo version: 2.5.3, current host: 11.11.11.111
com.alibaba.dubbo.remoting.ExecutionException: class com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler error when process caught event .
        at com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler.caught(AllChannelHandler.java:67)
        at com.alibaba.dubbo.remoting.transport.AbstractChannelHandlerDelegate.caught(AbstractChannelHandlerDelegate.java:44)
        at com.alibaba.dubbo.remoting.transport.AbstractChannelHandlerDelegate.caught(AbstractChannelHandlerDelegate.java:44)
        at com.alibaba.dubbo.remoting.transport.AbstractPeer.caught(AbstractPeer.java:127)
        at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.exceptionCaught(NettyHandler.java:112)
        at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.exceptionCaught(NettyCodecAdapter.java:165)
        at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:432)
        at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:52)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
        at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:148)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:351)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:282)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:202)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
Caused by: java.util.concurrent.RejectedExecutionException: Thread pool is EXHAUSTED! Thread Name: DubboServerHandler-11.11.11.111:41538, Pool Size: 500 (active: 500, core: 500, max: 500, largest: 500), Task: 154422 (completed: 153922), Executor status:(isShutdown:false, isTerminated:false, isTerminating:false), in dubbo://11.11.11.111:41538!
        at com.alibaba.dubbo.common.threadpool.support.AbortPolicyWithReport.rejectedExecution(AbortPolicyWithReport.java:53)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
        at com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler.caught(AllChannelHandler.java:65)
        ... 17 common frames omitted
```

**Comment by lovepoem** [comment]
First check why "dubbo Thread pool is EXHAUSTED !" qps is too big?

Then you can adjust thread properly,eg:
```xml
<dubbo:protocol name="dubbo" theads = "300"/>
```

**Comment by qinliujie** [comment]
Do you have use new version Dubbo?If you have done that, you could see your application where been blocked by check dubbo jstack file in dubbo log path !

**Comment by beiwei30** [comment]
Hi Victor,

Is it possible to write a simple spring boot application to reproduce the issue? Once you manage to dup the issue, pls. provide us github location, then we could investigate if there's any thread leak in dubbo code.

Thanks,
-Ian.

**Comment by chickenlj** [comment]
`
Caused by: java.util.concurrent.RejectedExecutionException: Thread pool is EXHAUSTED! Thread Name: DubboServerHandler-11.11.11.111:41538, Pool Size: 500 (active: 500, core: 500, max: 500, largest: 500), Task: 154422 (completed: 153922), Executor status:(isShutdown:false, isTerminated:false, isTerminating:false), in dubbo://11.11.11.111:41538!
        at com.alibaba.dubbo.common.threadpool.support.AbortPolicyWithReport.rejectedExecution(AbortPolicyWithReport.java:53)
`

Mostly, this happens when your  application blocks. I think you should first check your jstack. 
If you can upgrade to 2.5.7, the jstack file will be automically dumped to the specific path.
